### ISSUE TITLE
DBConnection.ConnectionError: connection not available because of disconnection

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact-api#130]
View details in Rollbar: [https://rollbar.com/captainfact/CaptainFact-API/items/20/](https://rollbar.com/captainfact/CaptainFact-API/items/20/)

```
Traceback (most recent call last):
  File "lib/db_connection.ex", line 934, in DBConnection.checkout/2 (db_connection)
  File "lib/db_connection.ex", line 750, in DBConnection.run/3 (db_connection)
  File "lib/db_connection.ex", line 644, in DBConnection.execute/4 (db_connection)
  File "lib/ecto/adapters/postgres/connection.ex", line 98, in Ecto.Adapters.Postgres.Connection.execute/4 (ecto)
  File "lib/ecto/adapters/sql.ex", line 256, in Ecto.Adapters.SQL.sql_call/6 (ecto)
  File "lib/ecto/adapters/sql.ex", line 436, in Ecto.Adapters.SQL.execute_or_reset/7 (ecto)
  File "lib/ecto/repo/queryable.ex", line 133, in Ecto.Repo.Queryable.execute/5 (ecto)
  File "lib/ecto/repo/queryable.ex", line 37, in Ecto.Repo.Queryable.all/4 (ecto)
DBConnection.ConnectionError: connection not available because of disconnection
```

**Comment by Betree** [comment]
Probably because disk is full. Old docker images should be pruned
