### ISSUE TITLE
GenServer terminating (MatchError): no match of right hand side value: {:error, :cannot_create_table}

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact-api#134]
View details in Rollbar: [https://rollbar.com/captainfact/CaptainFact-API/items/26/](https://rollbar.com/captainfact/CaptainFact-API/items/26/)

```
Traceback (most recent call last):
  File "lib/tzdata/ets_holder.ex", line 59, in Tzdata.EtsHolder.load_ets_table/1 (tzdata)
  File "lib/tzdata/ets_holder.ex", line 52, in Tzdata.EtsHolder.load_release/0 (tzdata)
  File "lib/tzdata/ets_holder.ex", line 23, in Tzdata.EtsHolder.handle_cast/2 (tzdata)
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4 (stdlib)
  File "gen_server.erl", line 711, in :gen_server.handle_msg/6 (stdlib)
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3 (stdlib)
GenServer terminating (MatchError): no match of right hand side value: {:error, :cannot_create_table}
```

**Comment by Betree** [comment]
Duplicate of https://github.com/CaptainFact/captain-fact-api/issues/135
